service: weboodi-scraper-lambda

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 150
  region: eu-central-1
  uploadBucket: kurssim.me
  environment:
    BUCKET_NAME: ${self:provider.uploadBucket}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - "arn:aws:s3:::${self:provider.uploadBucket}/hy_courses.json"

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  crawl:
    handler: handler.crawl
    package:
      include:
        - hy_scraper/**/*.py
    events:
      - schedule: rate(24 hours)

plugins:
  - serverless-python-requirements